version: 2

mkdocs:
  configuration: mkdocs.yml    
  fail_on_warning: false        

formats:                        
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"             
    nodejs: "20"

  jobs:
    post_install:               
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
    post_build:                
      - npm run build:docs
